<h1>Login</h1>

<?php
$username = $form->get('username');
$username->setAttribute('class','form-control');

$password = $form->get('password');
$password->setAttribute('class','form-control');

$submit = $form->get('submit');
$submit->setAttributes(['class'=>'btn btn-primary','value'=>'Entrar']);

$form->setAttribute('action',$this->url('login'));
$form->prepare();
?>


<?php echo $this->form()->openTag($form);?>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <?=$this->formLabel($username);?>
            <?=$this->formElement($username);?>
        </div>

        <div class="form-group">
            <?=$this->formLabel($password);?>
            <?=$this->formElement($password);?>
        </div>

        <?php
        echo $this->formSubmit($submit);
        echo $this->form()->closeTag($form);
        ?>
    </div>
</div>


